# iam_roles.tf
# Creates IAM roles for each tenant/role combination.
# Run: terraform apply -var="tenant_id=fintech-prod"

variable "tenant_id" {
  description = "Tenant identifier, e.g. fintech-prod"
  type        = string
}

variable "sso_provider" {
  description = "SSO provider: cognito or auth0"
  type        = string
  default     = "cognito"
}

variable "aws_region" {
  type    = string
  default = "us-east-1"
}

locals {
  roles = ["admin", "developer", "analyst", "readonly"]
}

# Permission boundary — applied to all roles
resource "aws_iam_policy" "boundary" {
  name        = "${var.tenant_id}-permission-boundary"
  description = "Permission boundary for all ${var.tenant_id} roles"
  policy = templatefile("${path.module}/boundary_policy.json.tpl", {
    tenant_id = var.tenant_id
  })
}

# One role per tier
resource "aws_iam_role" "tenant_roles" {
  for_each = toset(local.roles)

  name                 = "${var.tenant_id}-${each.key}"
  description          = "IAM role for ${var.tenant_id} ${each.key} users"
  permissions_boundary = aws_iam_policy.boundary.arn
  max_session_duration = 3600

  assume_role_policy = templatefile(
    "${path.module}/trust_policy_${var.sso_provider}.json.tpl",
    { tenant_id = var.tenant_id }
  )

  tags = {
    tenant_id   = var.tenant_id
    role        = each.key
    managed_by  = "terraform"
    project     = "iam-framework"
  }
}

# Inline policies generated by the Python generator
resource "aws_iam_role_policy" "tenant_policies" {
  for_each = toset(local.roles)

  name   = "${each.key}-policy"
  role   = aws_iam_role.tenant_roles[each.key].id
  policy = file("${path.module}/../out/${var.tenant_id}_${each.key}_policy.json")
}

output "role_arns" {
  value = { for r, role in aws_iam_role.tenant_roles : r => role.arn }
}
